# Generated by Django 4.2.2 on 2023-11-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='valor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hospedagem',
            name='valor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='apartamento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='valor',
            field=models.FloatField(),
        ),
    ]
